PORTNAME=	trafficmap
#DISTVERSIONPREFIX=	v
#DISTVERSION=	0.0.1
DISTVERSION=	g20250122
CATEGORIES=	sysutils

USE_GITHUB=	yes
GH_ACCOUNT=	tuaris
GH_TAGNAME=	91b8207

MAINTAINER=	daniel@morante.net
COMMENT=	Generates remap.config for Apache Traffic Server using DNS SRV records
WWW=		http://www.pacyworld.com

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	LICENSE

PLIST_FILES=	bin/trafficmap

PORTDOCS=	README.md

.include <bsd.port.mk>

